[project]
name = "brueckio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argon2-cffi==21.3.0",
    "django==5.2.*",
    "django-environ==0.13.0",
    "gunicorn==26.0.*",
    "pip>=26.1.2",
    "psycopg[binary]>=3.3.4",
    "sentry-sdk>=2.61.1",
    "wagtail==7.4.*",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.0.0",
    "django-extensions>=3.2.3",
]