# Generated by Django 3.2.12 on 2023-01-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitespecificjssettings_sitespecificsocialmediasettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitespecificjssettings',
            options={'verbose_name': 'JS Settings'},
        ),
        migrations.AlterModelOptions(
            name='sitespecificsocialmediasettings',
            options={'verbose_name': 'Social Media Settings'},
        ),
    ]
