# Generated by Django 2.0.9 on 2019-07-22 13:51

import brueckio.pages.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190722_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', brueckio.pages.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', brueckio.pages.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectoverviewpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', brueckio.pages.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', brueckio.pages.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
