# Generated by Django 2.0.9 on 2019-09-09 13:40

import brueckio.pages.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190722_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.AddField(
            model_name='homepage',
            name='introduction',
            field=wagtail.fields.RichTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectoverviewpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.CharBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', brueckio.pages.blocks.HeadingBlock()), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.blocks.CharBlock())]))], blank=True, null=True),
        ),
    ]
