# Generated by Django 2.2.9 on 2020-01-23 11:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_projectpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='description',
            field=wagtail.core.fields.RichTextField(default='description'),
            preserve_default=False,
        ),
    ]
