# Generated by Django 2.2.9 on 2020-01-28 11:02

import brueckio.pages.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_projectpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50))])), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('lead_text', brueckio.pages.blocks.LeadTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])), ('cv', wagtail.core.blocks.StructBlock([('when', wagtail.core.blocks.CharBlock()), ('what', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectoverviewpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50))])), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('lead_text', brueckio.pages.blocks.LeadTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])), ('cv', wagtail.core.blocks.StructBlock([('when', wagtail.core.blocks.CharBlock()), ('what', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.ChoiceBlock(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], label='Header Size')), ('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50))])), ('rich_text', brueckio.pages.blocks.RichTextBlock()), ('lead_text', brueckio.pages.blocks.LeadTextBlock()), ('contact_teaser', brueckio.pages.blocks.ContactTeaserBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.CharBlock())])), ('cv', wagtail.core.blocks.StructBlock([('when', wagtail.core.blocks.CharBlock()), ('what', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
