# Generated by Django 2.2.13 on 2021-10-08 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0008_auto_20211008_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FullWidthContentPage',
            new_name='ContactPage',
        ),
    ]
