# Generated by Django 3.2.12 on 2022-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_testimonial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
