# Generated by Django 3.2.12 on 2023-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20230105_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heropage',
            name='hero',
        ),
        migrations.AddField(
            model_name='heropage',
            name='hero_text',
            field=models.TextField(default='Hero title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heropage',
            name='hero_title',
            field=models.TextField(default='Hero Text'),
            preserve_default=False,
        ),
    ]
